---
- name: Install Elk
  hosts: elk
  become: true
  remote_user: azureuser
  tasks:
  - name: Set VM Max
    sysctl:
      name: vm.max_map_count
      value: '262144'
      sysctl_set: yes
      state: present
      reload: yes
  - name: Install docker.io
    apt:
      force_apt_get: yes
      update_cache: yes
      name: docker.io
      state: present
  - name: Install python3
    apt:
      name: python3-pip
      state: present
  - name: Install pip3
    apt:
      force_apt_get: yes
      name: python3-pip
      state: present
  - name: Install docker python client
    pip:
      name: docker
      state: present
  - name: download and launch a docker web container
    docker_container:
      name: sebpelk
      image: sebp/elk:761
      state: started
      restart_policy: always
      published_ports:
          - 5601:5601
          - 9200:9200
          - 5044:5044
  - name: Enable docker service
    systemd:
      name: docker
